// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/file_management/data/models/file_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2933503222850296189),
      name: 'File',
      lastPropertyId: const obx_int.IdUid(9, 2198361206089323603),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3462129818280163342),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6558802783405580143),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9106844457950300752),
            name: 'hash',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5307462514647557182),
            name: 'mimeType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2704966603259477581),
            name: 'sizeInBytes',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2498238307875495402),
            name: 'timeCreated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3157540112820488283),
            name: 'timeLastModified',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5480118627372021280),
            name: 'dbTimeCreated',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2198361206089323603),
            name: 'dbTimeLastModified',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 2933503222850296189),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    File: obx_int.EntityDefinition<File>(
        model: _entities[0],
        toOneRelations: (File object) => [],
        toManyRelations: (File object) => {},
        getId: (File object) => object.id,
        setId: (File object, int id) {
          object.id = id;
        },
        objectToFB: (File object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final hashOffset = fbb.writeString(object.hash);
          final mimeTypeOffset = fbb.writeString(object.mimeType);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, hashOffset);
          fbb.addOffset(3, mimeTypeOffset);
          fbb.addInt64(4, object.sizeInBytes);
          fbb.addInt64(5, object.timeCreated.millisecondsSinceEpoch);
          fbb.addInt64(6, object.timeLastModified.millisecondsSinceEpoch);
          fbb.addInt64(7, object.dbTimeCreated);
          fbb.addInt64(8, object.dbTimeLastModified);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = File()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..hash = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..mimeType = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..sizeInBytes =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..timeCreated = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0))
            ..timeLastModified = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0))
            ..dbTimeCreated =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
            ..dbTimeLastModified =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [File] entity fields to define ObjectBox queries.
class File_ {
  /// See [File.id].
  static final id = obx.QueryIntegerProperty<File>(_entities[0].properties[0]);

  /// See [File.name].
  static final name = obx.QueryStringProperty<File>(_entities[0].properties[1]);

  /// See [File.hash].
  static final hash = obx.QueryStringProperty<File>(_entities[0].properties[2]);

  /// See [File.mimeType].
  static final mimeType =
      obx.QueryStringProperty<File>(_entities[0].properties[3]);

  /// See [File.sizeInBytes].
  static final sizeInBytes =
      obx.QueryIntegerProperty<File>(_entities[0].properties[4]);

  /// See [File.timeCreated].
  static final timeCreated =
      obx.QueryDateProperty<File>(_entities[0].properties[5]);

  /// See [File.timeLastModified].
  static final timeLastModified =
      obx.QueryDateProperty<File>(_entities[0].properties[6]);

  /// See [File.dbTimeCreated].
  static final dbTimeCreated =
      obx.QueryIntegerProperty<File>(_entities[0].properties[7]);

  /// See [File.dbTimeLastModified].
  static final dbTimeLastModified =
      obx.QueryIntegerProperty<File>(_entities[0].properties[8]);
}
