// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/file_management/data/models/file_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2933503222850296189),
      name: 'File',
      lastPropertyId: const obx_int.IdUid(15, 2745319765034613164),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3462129818280163342),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8683618238728532890),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2713778461944599971),
            name: 'hash',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 6699308637826693896)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 8180727755434864447),
            name: 'mimeType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2911965324716622281),
            name: 'sizeInBytes',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 97400929135809652),
            name: 'timeCreated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2745319765034613164),
            name: 'timeLastModified',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 2933503222850296189),
      lastIndexId: const obx_int.IdUid(1, 6699308637826693896),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6558802783405580143,
        9106844457950300752,
        5307462514647557182,
        2704966603259477581,
        2498238307875495402,
        3157540112820488283,
        5480118627372021280,
        2198361206089323603
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    File: obx_int.EntityDefinition<File>(
        model: _entities[0],
        toOneRelations: (File object) => [],
        toManyRelations: (File object) => {},
        getId: (File object) => object.id,
        setId: (File object, int id) {
          object.id = id;
        },
        objectToFB: (File object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final hashOffset = fbb.writeString(object.hash);
          final mimeTypeOffset = fbb.writeString(object.mimeType);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(9, nameOffset);
          fbb.addOffset(10, hashOffset);
          fbb.addOffset(11, mimeTypeOffset);
          fbb.addInt64(12, object.sizeInBytes);
          fbb.addInt64(13, object.timeCreated.millisecondsSinceEpoch);
          fbb.addInt64(14, object.timeLastModified.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 22, '');
          final hashParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final mimeTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final sizeInBytesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final timeCreatedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0));
          final timeLastModifiedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0));
          final object = File(nameParam, hashParam, mimeTypeParam,
              sizeInBytesParam, timeCreatedParam, timeLastModifiedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [File] entity fields to define ObjectBox queries.
class File_ {
  /// See [File.id].
  static final id = obx.QueryIntegerProperty<File>(_entities[0].properties[0]);

  /// See [File.name].
  static final name = obx.QueryStringProperty<File>(_entities[0].properties[1]);

  /// See [File.hash].
  static final hash = obx.QueryStringProperty<File>(_entities[0].properties[2]);

  /// See [File.mimeType].
  static final mimeType =
      obx.QueryStringProperty<File>(_entities[0].properties[3]);

  /// See [File.sizeInBytes].
  static final sizeInBytes =
      obx.QueryIntegerProperty<File>(_entities[0].properties[4]);

  /// See [File.timeCreated].
  static final timeCreated =
      obx.QueryDateProperty<File>(_entities[0].properties[5]);

  /// See [File.timeLastModified].
  static final timeLastModified =
      obx.QueryDateProperty<File>(_entities[0].properties[6]);
}
